### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by rafaelanastacioalves** [DangLienMinh/webrtc_client#1]
Hi, (it's me again) 
could you help me to solve this problem? After registering or trying to click in login, I cannot succeed and get something like this:
![image](https://cloud.githubusercontent.com/assets/5789073/16536798/667e1124-3fcd-11e6-9385-86b3c875b95a.png)

**Comment by minhdl93** [comment]
Hi @rafaelanastacioalves ,

Have you started mongo db yet?
It looks like the connection to db is refused.

**Comment by rafaelanastacioalves** [comment]
Well, I'm pretty sure I've started it.
1 - I called _sudo mongod_
2 - I called _sudo sudo npm start_ on another tab.
I know that using _sudo_ isn't recommended... but I don't think it is important here...
Here follows the prints from the calls:
![image](https://cloud.githubusercontent.com/assets/5789073/16571085/dde73ba6-4229-11e6-8933-14fbc10f92af.png)

![image](https://cloud.githubusercontent.com/assets/5789073/16571087/eab0d09a-4229-11e6-91ac-778756f622d9.png)

**Comment by minhdl93** [comment]
Hi @rafaelanastacioalves,
 Have you changed the host to localhost and port to 3000 in app/src/main/res/values/strings.xml yet?

**Comment by rafaelanastacioalves** [comment]
Yes...
![image](https://cloud.githubusercontent.com/assets/5789073/16603154/585a8c5a-42f0-11e6-8aa3-abb3c73f12c3.png)

**Comment by rafaelanastacioalves** [comment]
Hi,
It's fine. I used ip adress 127.0.0.1, which is probably known by the server as localhost, but it could have some issues when using the app on wifi. So I used the ip adress given by the system: 
![image](https://cloud.githubusercontent.com/assets/5789073/16603464/a7f72e2e-42f2-11e6-9a57-60aefc64d25e.png)
And It worked! 
Thanks for the help. You may delete this issue...
