### ISSUE TITLE
How to improve audio quality?

### ISSUE THREAD

**Issue by sriharisri** [DangLienMinh/webrtc_client#3]
Hi sir,
  I am importing your webrtc_client project in my android environment.Now video call working fine.But not fine with audio.how to increase speakers volume while video call is running . Which type of audio codecs used in webrtc .

**Comment by minhdl93** [comment]
Dear sriharianu,

Currently I used OPUS codec. You can find out more about it here https://www.webrtcexample.com/blog/?go=all/which-audio-and-video-codecs-can-be-used-in-a-webrtc-application/.

I think webRTC support the function to increase the volume, please visit webRTC developer site for more function,

**Comment by Longstreet** [comment]
audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
        audioManager.setSpeakerphoneOn(true);

Depending on what exactly you wish to accomplish and how big of a boost you want/need, those two lines could probably help you figure out what you want to do. I suggest reading up on the audioManager as it has a lot of functions that you might want to use.
