### ISSUE TITLE
Video appears black between device and emulator

### ISSUE THREAD

**Issue by mkmlh** [DangLienMinh/webrtc_client#5]
Video goes black between device and emulator, is it because the emulator don't have a camera? so both of them not showing up any video ?
Or i have to edit RtcActivity.java ? 
Thank you

**Comment by minhdl93** [comment]
Have you set up the ip address correctly. In addition, try to test on the emulator which has the camera.

**Comment by mkmlh** [comment]
i had tested to both devices that have camera. But only one side client that show up the camera, neither the other client only show up the black screen. I have set IP address correctly too

**Comment by minhdl93** [comment]
Hi @imkamalh , from line 707 to 716 in MainActivity.java. Please change delay 3000 to 5000 or longer, maybe it will fix the problem

public void startHandler() {
        handler.postDelayed(new Runnable() {

            @Override
            public void run() {
                checkFriendStatus();
                handler.postDelayed(this, 3000);
            }
        }, 3000);
    }

**Comment by mkmlh** [comment]
Still not solving the problem :( 
https://cloud.githubusercontent.com/assets/20569475/24835615/befcfa5e-1d30-11e7-9bf3-5e9b402e689c.jpg

My device runs Nougat and Lollipop. I think its not matter lol... the thing is maybe remoteRender and localRender problems at RtcActivity.java, but i don't know how...

Btw i want to studying your program as my end year project, i'll be very glad if this program can run smoothly 👍

**Comment by minhdl93** [comment]
I am sorry that I can not help you in this problem. I've done this project 2 years ago. So I can't remember detail of them. Please try to search the document for the function. If you can fix this problem, please share them with the other here. Thank you

**Comment by mkmlh** [comment]
@DangLienMinh , someone solved at this link https://github.com/GleasonK/AndroidRTC/issues/3
he put if condition when peer know each id target

 `boolean connect(String userId, boolean dialed) {`  
 `       if (!peers.containsKey(userId)) { // Prevents duplicate dials.` 
  `           if (peers.size() < MAX_CONNECTIONS) {` 
    `             Log.i("connect", "iki konek bos");` 
      `           PnPeer peer = addPeer(userId);` 
      `           peer.pc.addStream(this.localMediaStream);` 
      `           try {` 
      `               if(!dialed) {` 
      `                   actionMap.get(CreateOfferAction.TRIGGER).execute(userId, new JSONObject());` 
      `                   Log.i("emosi", "jeh keno dial ?");` 
      `                   Log.i("tetep emosi", ""+dialed);` 
      `               }` 
      `           } catch (JSONException e){` 
      `               e.printStackTrace();` 
      `               return false;
                 }
                 return true;
             }
         } ` 

Which can refer to your code at **WebRtcClient.java**, maybe u know where u can put it on?

**Comment by minhdl93** [comment]
Dear @imkamalh, Because my project don't have the same problem, so maybe I don't need to add this extra code. Thank you very much for your kind remind
