### ISSUE TITLE
Audio is not streamed with video

### ISSUE THREAD

**Issue by SWebvillee** [DangLienMinh/webrtc_client#6]
my audio is not transferred or listened from both end but video works fine

**Comment by minhdl93** [comment]
![dddd](https://cloud.githubusercontent.com/assets/2697347/25648405/7e15e4b8-3006-11e7-95f2-2e39ca9fe36e.PNG)

The code for audio implement is here, so I don't know why the problem appears, Could you please try to restart the server, and then try to test the two devices with skype or other application first to see if it works

**Comment by SWebvillee** [comment]
Hey! thanks for the reply my problem got resolved by restarting the server.

**Comment by minhdl93** [comment]
you're welcome, issue closed
