### ISSUE TITLE
Only audio calling

### ISSUE THREAD

**Issue by SWebvillee** [DangLienMinh/webrtc_client#7]
If we want to implement only audio calling then how to achieve that on receiving end. If at sending end we comment the following lines -  

if (pcParams.videoCallEnabled) {
            MediaConstraints videoConstraints = new MediaConstraints();
            videoConstraints.mandatory.add(new MediaConstraints.KeyValuePair("maxHeight", Integer.toString(pcParams.videoHeight)));
            videoConstraints.mandatory.add(new MediaConstraints.KeyValuePair("maxWidth", Integer.toString(pcParams.videoWidth)));
            videoConstraints.mandatory.add(new MediaConstraints.KeyValuePair("maxFrameRate", Integer.toString(pcParams.videoFps)));
            videoConstraints.mandatory.add(new MediaConstraints.KeyValuePair("minFrameRate", Integer.toString(pcParams.videoFps)));
            videoSource = factory.createVideoSource(getVideoCapturer(), videoConstraints);
            localMS.addTrack(factory.createVideoTrack("ARDAMSv0", videoSource));
        }
![7e15e4b8-3006-11e7-95f2-2e39ca9fe36e](https://cloud.githubusercontent.com/assets/28294936/25663759/2a809642-3036-11e7-8274-0d1ec40bc26d.PNG)

**Comment by minhdl93** [comment]
Please check the function stop video. I did implement the stop video calling on the screen when you make a call. Please check it out 

https://github.com/DangLienMinh/webrtc_client/blob/master/app/src/main/java/fr/pchab/androidrtc/RtcActivity.java
![dsdsdsds](https://cloud.githubusercontent.com/assets/2697347/25686407/de985224-30a8-11e7-9f36-a98e8587b429.PNG)
