### ISSUE TITLE
Video Calling Services not working after generating Signed APK

### ISSUE THREAD

**Issue by sriharisri** [DangLienMinh/webrtc_client#8]
Hi,

This is Srihari, currently working on Video & Audio calling features for an being developed from our end.

While generating signed apk for the application which i am developing currently gives an error which is stated below .. can you please help me out with possible solution if any

Looking forward to here from you

regards
srihari
![screenshot_2018-04-24-09-59-32-340_com miui bugreport](https://user-images.githubusercontent.com/15214304/39171189-a123b6ba-47bb-11e8-84b4-9a6bdc01ff7f.png)

**Comment by minhdl93** [comment]
Sorry I have no idea where this problem comes from. 

Maybe this post can help you https://stackoverflow.com/questions/11369301/android-libc-so-crash

**Comment by minhdl93** [comment]
Issue closed
